# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad8ba9ebd792fc7aea3ec8303ba5c12c4087f6e45a936afe168192ba7099753799c9d0713576b153f42bd093b447c5eece492ea7fc9eb723d076fa184045d01

test:
  secret_key_base: 3bc5f37bbeca6ca84ed56c2f54d8b623c65ff99796e00c7ca62db5b9272c4acc6b49ddf40d6c398e61d68ffcf1cab0ad3c6d27d4ffe27afbd5520b100fdb8272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
